services:
  - type: web
    name: mtle-study-bot
    env: python
    buildCommand: |
      # Update and install system dependencies
      apt-get update && apt-get install -y fontconfig wget unzip
      # Create font directory
      mkdir -p /usr/share/fonts/truetype/poppins
      # Download and install Poppins fonts
      wget https://fonts.google.com/download?family=Poppins -O poppins.zip
      unzip poppins.zip -d poppins
      cp poppins/*.ttf /usr/share/fonts/truetype/poppins/
      fc-cache -f -v
      rm -rf poppins poppins.zip
      # Install Python dependencies
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /health
    healthCheckPort: 10001
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: 10000
      - key: HEALTH_CHECK_PORT
        value: 10001
      - key: TELEGRAM_TOKEN
        sync: false
