services:
  - type: web
    name: study-bot
    env: docker  # Changed to docker since you have a Dockerfile
    region: singapore  # Added for better latency in Asia
    plan: free
    buildCommand: null  # Remove buildCommand since we're using Dockerfile
    startCommand: null  # Remove startCommand since it's in Dockerfile
    healthCheckPath: /health
    healthCheckPort: 10001  # Explicitly set health check port
    autoDeploy: true  # Added for automatic deployments
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: 10000
      - key: HEALTH_CHECK_PORT
        value: 10001
      - key: TELEGRAM_TOKEN
        sync: false  # This will be set manually in Render dashboard
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
      targetCPUPercent: 80
