services:
  - type: web
    name: study-bot
    env: python
    region: ohio
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: pkill -f "python bot.py" || true && python bot.py
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: DEBUG_MODE
        value: "False"
      - key: PORT
        value: 10000
      - key: WEBHOOK_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: TZ
        value: UTC
      - key: USE_WEBHOOK
        value: "True"
    autoDeploy: true
