services:
  - type: web
    name: mtle-study-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && python bot.py
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
