services:
  - type: web
    name: study-bot
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p /app/fonts
      cp Poppins-*.ttf /app/fonts/
    startCommand: python bot.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PORT
        value: 10000
