services:
  - type: web
    name: mtle-study-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gevent --workers 1 --bind 0.0.0.0:10001 bot:app
    plan: free
    healthCheckPath: /health
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: HEALTH_CHECK_PORT
        value: 10001
      - key: TZ
        value: Asia/Manila
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: "true"
