# Current information
CURRENT_USER = "Zackrmt"
STARTUP_TIME = "2025-06-04 19:37:49"

# Conversation states
(CHOOSING_MAIN_MENU,
 SETTING_GOAL,
 CONFIRMING_GOAL,
 CHOOSING_SUBJECT,
 STUDYING,
 ON_BREAK,
 CREATING_QUESTION,
 SETTING_CHOICES,
 CONFIRMING_QUESTION,
 SETTING_CORRECT_ANSWER,
 SETTING_EXPLANATION,
 CHOOSING_DESIGN,
 CHOOSING_QUESTION_SUBJECT,
 CONFIRMING_DELETION) = range(14)
